-- TontiGest — schéma de base de données
--
-- Depuis la migration vers le backend local (Express + MySQL), le schéma de
-- référence est `server/schema.sql` (DDL MySQL : users, clubs, records).
-- Il est appliqué automatiquement :
--   • au lancement du serveur (`npm start` / `npm run server`) ;
--   • ou via `npm run setup-db` (création de la base + schéma + données de démo).
--
-- Ce fichier est conservé comme point d'entrée historique du dossier db/.
-- Voir README.md pour les prérequis (MySQL local) et la configuration (.env).
